"""change nulls and added campaign

Revision ID: 46c0999e44c6
Revises: 8db5b4c5e2cc
Create Date: 2024-03-11 13:14:22.165122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c0999e44c6'
down_revision = '8db5b4c5e2cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_index('ix_lead_name')
        batch_op.create_index(batch_op.f('ix_lead_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_name'))
        batch_op.create_index('ix_lead_name', ['name'], unique=False)
        batch_op.alter_column('state',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
        batch_op.drop_column('lead_type')

    # ### end Alembic commands ###
