"""added field other_fields

Revision ID: 68215bee748d
Revises: 19b727c50e65
Create Date: 2024-03-14 16:11:26.536476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68215bee748d'
down_revision = '19b727c50e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_fields', sa.JSON(), nullable=True))
        batch_op.alter_column('primary_goal',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.alter_column('primary_goal',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('other_fields')

    # ### end Alembic commands ###
